<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>

# Assignment:

- Replicate the lesson code.

 - This means that if you haven't followed along already, type out the things that we did in class. Forcing your fingers to hit each key will help you internalize the syntax of what we're doing. Make sure you understand each line of code that you're writing, google things that you don't fully understand.
 - [Lambda Learning Method for DS - By Ryan Herr](https://docs.google.com/document/d/1ubOw9B3Hfip27hF2ZFnW3a3z9xAgrUDRReOEo-FHCVs/edit?usp=sharing)
- Convert the `term` column from string to integer.
- Make a column named `loan_status_is_great`. It should contain the integer 1 if `loan_status` is "Current" or "Fully Paid." Else it should contain the integer 0.
- Make `last_pymnt_d_month` and `last_pymnt_d_year` columns.

In [3]:
##### Begin Working Here #####
#import zip files into colab
!wget https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip

--2020-01-14 21:05:09--  https://resources.lendingclub.com/LoanStats_2018Q4.csv.zip
Resolving resources.lendingclub.com (resources.lendingclub.com)... 64.48.1.20
Connecting to resources.lendingclub.com (resources.lendingclub.com)|64.48.1.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘LoanStats_2018Q4.csv.zip’

LoanStats_2018Q4.cs     [         <=>        ]  21.72M  1.84MB/s    in 12s

2020-01-14 21:05:21 (1.82 MB/s) - ‘LoanStats_2018Q4.csv.zip’ saved [22776791]

In [4]:
#unzip the .zip file to have access to the csv file
!unzip LoanStats_2018Q4.csv.zip

Archive:  LoanStats_2018Q4.csv.zip
  inflating: LoanStats_2018Q4.csv

In [6]:
#create a dataframe using the csv that we got from the zip file
df = pd.read_csv('LoanStats_2018Q4.csv')
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0,1,2,3,4,7,13,18,19,24,25,27,28,29,30,31,32,34,36,37,38,39,40,41,42,43,44,46,49,50,51,53,54,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,113,114,115,116,117,118,119,120,121,126,127,131,132,134,135,136,141,142,143) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Notes offered by Prospectus (https://www.lendingclub.com/info/prospectus.action)
id  member_id loan_amnt funded_amnt funded_amnt_inv term       int_rate installment grade sub_grade emp_title           emp_length home_ownership annual_inc verification_status issue_d  loan_status pymnt_plan url desc purpose            title                   zip_code addr_state dti   delinq_2yrs earliest_cr_line inq_last_6mths mths_since_last_delinq mths_since_last_record open_acc pub_rec revol_bal revol_util total_acc initial_list_status out_prncp out_prncp_inv total_pymnt     total_pymnt_inv total_rec_prncp total_rec_int total_rec_late_fee recoveries collection_recovery_fee last_pymnt_d last_pymnt_amnt next_pymnt_d last_credit_pull_d collections_12_mths_ex_med mths_since_last_major_derog policy_code application_type annual_inc_joint dti_joint verification_status_joint acc_now_delinq tot_coll_amt tot_cur_bal open_acc_6m open_act_il open_il_12m open_il_24m mths_since_rcnt_il total_bal_il il_util open_rv_12m open_rv_24m max_bal_bc all_util total_rev_hi_lim inq_fi total_cu_tl inq_last_12m acc_open_past_24mths avg_cur_bal bc_open_to_buy bc_util chargeoff_within_12_mths delinq_amnt mo_sin_old_il_acct mo_sin_old_rev_tl_op mo_sin_rcnt_rev_tl_op mo_sin_rcnt_tl mort_acc mths_since_recent_bc mths_since_recent_bc_dlq mths_since_recent_inq mths_since_recent_revol_delinq num_accts_ever_120_pd num_actv_bc_tl num_actv_rev_tl num_bc_sats num_bc_tl num_il_tl num_op_rev_tl num_rev_accts num_rev_tl_bal_gt_0 num_sats num_tl_120dpd_2m num_tl_30dpd num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75 pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort total_bc_limit total_il_high_credit_limit revol_bal_joint sec_app_earliest_cr_line sec_app_inq_last_6mths sec_app_mort_acc sec_app_open_acc sec_app_revol_util sec_app_open_act_il sec_app_num_rev_accts sec_app_chargeoff_within_12_mths sec_app_collections_12_mths_ex_med sec_app_mths_since_last_major_derog hardship_flag hardship_type hardship_reason hardship_status deferral_term hardship_amount hardship_start_date hardship_end_date payment_plan_start_date hardship_length hardship_dpd hardship_loan_status orig_projected_additional_accrued_interest hardship_payoff_balance_amount hardship_last_payment_amount debt_settlement_flag debt_settlement_flag_date settlement_status settlement_date settlement_amount settlement_percentage                                    settlement_term
NaN NaN       6000      6000        6000             36 months  14.47%  206.44      C     C2        Manager             10+ years  RENT           55000      Verified            Dec-2018 Charged Off n          NaN NaN  credit_card        Credit card refinancing 104xx    NY         10.65 0           Jun-2006         0              NaN                    NaN                    6        0       4196      91.2%      8         w                   0.00      0.00          1106.52         1106.52         546.14          272.38        0.0                288.0      51.84                   Apr-2019     206.44          NaN          Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            12514       0           2           1           1           9                  8318         74      1           1           2807       79       4600             1      0           2            2                    2086        344            92      0                        0           33                 150                  9                     9              0        9                    NaN                      9                     NaN                            0                     3              4               3           3         3         4             5             4                   6        0                0            0                  2                  100            100              0                    0         15800           12514             4300           11200                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          Y                    Oct-2019                  ACTIVE            Oct-2019        3479              60.01                                                                 24
              24000     24000       24000            36 months  10.33%  778.14      B     B1        Maintenance Manager 10+ years  MORTGAGE       100000     Not Verified        Dec-2018 Current     n          NaN NaN  debt_consolidation Debt consolidation      606xx    IL         19.14 0           Oct-1996         3              39                     NaN                    14       0       8547      27.7%      28        w                   16807.30  16807.30      9317.02         9317.02         7192.70         2124.32       0.0                0.0        0.0                     Dec-2019     778.14          Jan-2020     Nov-2019           0                          57                          1           Individual       NaN              NaN       NaN                       0              0            273876      3           5           3           5           5                  40384        66      2           4           4368       51       30900            8      0           8            9                    19563       17353          33      0                        0           266                178                  4                     4              3        4                    39                       1                     39                             1                     5              5               6           8         15        7             9             5                   14       0                0            0                  5                  82.1           16.7             0                    0         335121          50686             25900          61514                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              30000     30000       30000            36 months  15.02%  1040.26     C     C3        Firefighter         10+ years  RENT           90000      Verified            Dec-2018 Fully Paid  n          NaN NaN  debt_consolidation Debt consolidation      681xx    NE         22.23 0           May-2007         1              NaN                    NaN                    8        0       25754     48%        23        w                   0.00      0.00          30883.673711683 30883.67        30000.00        883.67        0.0                0.0        0.0                     Feb-2019     28382.51        NaN          Nov-2019           0                          NaN                         1           Individual       NaN              NaN       NaN                       0              0            51370       1           2           1           2           9                  25616        71      2           3           9621       57       53600            0      2           1            5                    6421        22030          47      0                        0           123                139                  3                     3              3        3                    NaN                      3                     NaN                            0                     4              6               4           5         11        6             9             6                   8        0                0            0                  3                  100            50               0                    0         89849           51370             41600          36249                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN
              8000      8000        8000             36 months  12.98%  269.48      B     B5        Controller          4 years    MORTGAGE       95000      Source Verified     Dec-2018 Current     n          NaN NaN  credit_card        Credit card refinancing 480xx    MI         9.44  0           Mar-2009         2              73                     NaN                    7        0       11434     33.3%      20        w                   1707.34   1707.34       6855.63         6855.63         6292.66         562.97        0.0                0.0        0.0                     Dec-2019     269.48          Jan-2020     Dec-2019           0                          73                          1           Individual       NaN              NaN       NaN                       0              0            247933      5           1           3           4           2                  13716        98      4           5           8918       52       34300            2      0           7            10                   35419       22866          33.3    0                        0           13                 117                  6                     2              1        6                    73                       2                     73                             1                     3              3               5           15        4         5             15            3                   7        0                0            0                  8                  100            20               0                    0         271550          25150             34300          14000                      NaN             NaN                      NaN                    NaN              NaN              NaN                NaN                 NaN                   NaN                              NaN                                NaN                                 N             NaN           NaN             NaN             NaN           NaN             NaN                 NaN               NaN                     NaN             NaN          NaN                  NaN                                        NaN                            NaN                          N                    NaN                       NaN               NaN             NaN               NaN                                                                  NaN

In [19]:
#the column headers needed to be fixed 
df = pd.read_csv('LoanStats_2018Q4.csv', header=1)
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

    id  member_id  ...  settlement_percentage  settlement_term
0  NaN        NaN  ...                  60.01             24.0
1  NaN        NaN  ...                    NaN              NaN
2  NaN        NaN  ...                    NaN              NaN
3  NaN        NaN  ...                    NaN              NaN
4  NaN        NaN  ...                    NaN              NaN

[5 rows x 144 columns]

In [38]:
#checking for NaN's
pd.set_option('display.max_rows', 100)
df.isnull().sum().sort_values()

inq_fi                                             2
delinq_amnt                                        2
chargeoff_within_12_mths                           2
acc_open_past_24mths                               2
inq_last_12m                                       2
                                               ...
orig_projected_additional_accrued_interest    128193
id                                            128397
url                                           128399
member_id                                     128399
desc                                          128399
Length: 144, dtype: int64

In [120]:
#We need to remove the extra NaN's its creating
df = pd.read_csv('LoanStats_2018Q4.csv', header=1, skipfooter=2, engine='python')
df.isnull().sum().sort_values()

inq_fi                                             0
delinq_amnt                                        0
chargeoff_within_12_mths                           0
acc_open_past_24mths                               0
inq_last_12m                                       0
                                               ...
orig_projected_additional_accrued_interest    128191
url                                           128397
member_id                                     128397
desc                                          128397
id                                            128397
Length: 144, dtype: int64

In [121]:
#Making sure that the term column doesn't have any NaN values that could mess up the int conversion
df['term'].isnull().sum()

0

In [0]:
#function to take a variable and strip the spaces and the word "months"
def str_to_int (cell_contents):
  cell_contents = cell_contents.strip().strip('months').strip()
  return int(cell_contents)


#apply the str_to_int function to every cell of the term column
df['term'] = df['term'].apply(str_to_int)

In [123]:
#checking if term are ints and was stripped correctly
df['term'].head(5)

0    36
1    36
2    36
3    36
4    60
Name: term, dtype: int64

In [124]:
#created a empty list to be used to fill 1's and 0's in 
test = []
#for statement to check if the loan status is "Current" or "Fully Paid" and give it a 1 or 0
for status in df['loan_status']:
  if status == "Current" or status == "Fully Paid":
    test.append(1)
  else:
    test.append(0)
#created a column called "loan_status_is_great" and gave it the values of list
df['loan_status_is_great'] = test
df.head()

   id  member_id  ...  settlement_term  loan_status_is_great
0 NaN        NaN  ...             24.0                     0
1 NaN        NaN  ...              NaN                     1
2 NaN        NaN  ...              NaN                     1
3 NaN        NaN  ...              NaN                     1
4 NaN        NaN  ...              NaN                     1

[5 rows x 145 columns]

In [125]:
#The NaN values need to be replaced before its converted into datatime64
df['last_pymnt_d'].isnull().sum()

159

In [126]:
#Now that there are no NaN values, we don't have to worry about float values in the conversion
df['last_pymnt_d'] = df['last_pymnt_d'].fillna(0)
df['last_pymnt_d'].isnull().sum()

0

In [0]:
#convert the last_pymnt_d into datetime64 dtype so that it can be used to create other time columns
df['last_pymnt_d'] = pd.to_datetime(df['last_pymnt_d'], infer_datetime_format=True)

In [128]:
#Checking if the datatype converted correctly
#<M8[ns] == datatime64[ns]
df['last_pymnt_d'].dtypes

dtype('<M8[ns]')

In [0]:
#creating last_pymnt_d_month column
df['last_pymnt_d_month'] = df['last_pymnt_d'].dt.month

In [130]:
#double checking that there are no NaN values
df['last_pymnt_d_month'].isnull().sum()

0

In [0]:
#creating last_pymnt_d_year column
df['last_pymnt_d_year'] = df['last_pymnt_d'].dt.year

In [132]:
#final
df.head()

   id  member_id  ...  last_pymnt_d_month  last_pymnt_d_year
0 NaN        NaN  ...                   4               2019
1 NaN        NaN  ...                  12               2019
2 NaN        NaN  ...                   2               2019
3 NaN        NaN  ...                  12               2019
4 NaN        NaN  ...                  12               2019

[5 rows x 147 columns]

# Stretch Goals

You can do more with the LendingClub or Instacart datasets.

LendingClub options:
- There's one other column in the dataframe with percent signs. Remove them and convert to floats. You'll need to handle missing values.
- Modify the `emp_title` column to replace titles with 'Other' if the title is not in the top 20. 
- Take initiatve and work on your own ideas!

Instacart options:
- Read [Instacart Market Basket Analysis, Winner's Interview: 2nd place, Kazuki Onodera](http://blog.kaggle.com/2017/09/21/instacart-market-basket-analysis-winners-interview-2nd-place-kazuki-onodera/), especially the **Feature Engineering** section. (Can you choose one feature from his bulleted lists, and try to engineer it with pandas code?)
- Read and replicate parts of [Simple Exploration Notebook - Instacart](https://www.kaggle.com/sudalairajkumar/simple-exploration-notebook-instacart). (It's the Python Notebook with the most upvotes for this Kaggle competition.)
- Take initiative and work on your own ideas!

You can uncomment and run the cells below to re-download and extract the Instacart data

In [133]:
 !wget https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz

--2020-01-14 23:41:00--  https://s3.amazonaws.com/instacart-datasets/instacart_online_grocery_shopping_2017_05_01.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.11.102
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.11.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 205548478 (196M) [application/x-gzip]
Saving to: ‘instacart_online_grocery_shopping_2017_05_01.tar.gz’

instacart_online_gr 100%[===================>] 196.03M  44.3MB/s    in 4.8s

2020-01-14 23:41:05 (40.6 MB/s) - ‘instacart_online_grocery_shopping_2017_05_01.tar.gz’ saved [205548478/205548478]

In [134]:
 !tar --gunzip --extract --verbose --file=instacart_online_grocery_shopping_2017_05_01.tar.gz

instacart_2017_05_01/
instacart_2017_05_01/._aisles.csv
instacart_2017_05_01/aisles.csv
instacart_2017_05_01/._departments.csv
instacart_2017_05_01/departments.csv
instacart_2017_05_01/._order_products__prior.csv
instacart_2017_05_01/order_products__prior.csv
instacart_2017_05_01/._order_products__train.csv
instacart_2017_05_01/order_products__train.csv
instacart_2017_05_01/._orders.csv
instacart_2017_05_01/orders.csv
instacart_2017_05_01/._products.csv
instacart_2017_05_01/products.csv

In [135]:
 %cd instacart_2017_05_01

/content/instacart_2017_05_01